### ISSUE TITLE
RuntimeError: Invalid magic number; corrupt file?

### ISSUE THREAD

**Issue by Jiaoma** [ycxioooong/MovieSynopsisAssociation#1]
Hi, I'm interested in your proposed dataset. But the features you provided seems to be corrupted. I use the following code to read the feature:
`
path='/xxx/msa_data/feature/tt1907668.pkl'
import torch
a=torch.load(path)
print(a.shape)
`
The error information is:
`
Traceback (most recent call last):
  File "/home/molijuly/myProjects/ILoveMovie/test.py", line 4, in <module>
    a=torch.load(path)
  File "/home/molijuly/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/molijuly/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 766, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?
`
Is the problem with the feature files or the reading method?

**Comment by Jiaoma** [comment]
Hi, I use the mmcv.load as you do in your code, and the features are correctly loaded. No other questions, I close this issue.
